# Generated by Django 3.2.6 on 2021-08-18 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_funcionario_imagem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicos',
            new_name='Servico',
        ),
    ]
